# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 17:44
from __future__ import unicode_literals

import articles.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170121_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(default=datetime.datetime(2017, 1, 21, 17, 44, 59, 940513, tzinfo=utc), upload_to=articles.models.get_upload_file_name),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 21, 17, 44, 42, 370542, tzinfo=utc), verbose_name='date published'),
        ),
    ]
