# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 18:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170121_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 25, 18, 29, 19, 295018, tzinfo=utc), verbose_name='date published'),
        ),
    ]
